[build]
builder = "RAILPACK"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "ticketmesh-bot"

[services.source]
repo = "Elenyx/cautious-parakeet"
branch = "main"
rootDirectory = "packages/bot"

[services.variables]
NODE_ENV = "production"
PORT = "3000"