# TicketMesh Bot Service
[[services]]
name = "ticketmesh-bot"

[services.source]
repo = "Elenyx/cautious-parakeet"
branch = "main"
rootDirectory = "packages/bot"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.variables]
NODE_ENV = "production"

# TicketMesh Client Service
[[services]]
name = "ticketmesh-client"

[services.source]
repo = "Elenyx/cautious-parakeet"
branch = "main"
rootDirectory = "packages/client"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.variables]
NODE_ENV = "production"