# TicketMesh Bot Service
[[services]]
name = "ticketmesh-bot"

[services.source]
repo = "Elenyx/cautious-parakeet"
branch = "main"
rootDirectory = "packages/bot"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[services.variables]
NODE_ENV = "production"
PORT = "3001"
# Use Railway public proxy for Redis to avoid internal DNS resolution issues
REDIS_URL = "redis://default:uSJmhvtfgYyWUMrFrSGrcuUAVXQfkpvD@metro.proxy.rlwy.net:54279"
# IMPORTANT: Set these environment variables in Railway Dashboard:
# DISCORD_TOKEN = "your_discord_bot_token"
# DISCORD_CLIENT_ID = "your_discord_client_id"
# DATABASE_URL = "your_database_connection_string"
# API_SECRET = "your_api_secret_key"
# LOG_LEVEL = "info"

# TicketMesh Client Service  
[[services]]
name = "ticketmesh-client"

[services.source]
repo = "Elenyx/cautious-parakeet"
branch = "main"
rootDirectory = "packages/client"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[services.variables]
NODE_ENV = "production"
PORT = "3000"
BOT_API_BASE_URL = "https://ticketmesh-bot-production.up.railway.app"
# Use Railway public proxy for Redis to avoid internal DNS resolution issues
REDIS_URL = "redis://default:uSJmhvtfgYyWUMrFrSGrcuUAVXQfkpvD@metro.proxy.rlwy.net:54279"
# IMPORTANT: Set these environment variables in Railway Dashboard:
# API_SECRET = "your_api_secret_key" # Must match bot service API_SECRET
# NextAuth Configuration - SET THESE IN RAILWAY DASHBOARD
# NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
# NEXTAUTH_URL = "https://ticketmesh-production.up.railway.app"
# Discord OAuth Configuration - SET THESE IN RAILWAY DASHBOARD
# DISCORD_CLIENT_ID = "${{DISCORD_CLIENT_ID}}"
# DISCORD_CLIENT_SECRET = "${{DISCORD_CLIENT_SECRET}}"